const CFG=window.APP_CONFIG||{};
const PAYMENT_TYPES=['Account','Card on Collection','Cash on Collection','Account Credit','Bank Transfer','Other'];
const PICK_STATUSES=['Waiting','Picking','Ready','Problem','Cancelled'];
const AVATARS=['👨🏻','👩🏻','👨🏽','👩🏽','👨🏿','👩🏿'];
const state={user:null,token:'',bookings:[],team:[],activity:[],config:{VAT_PERCENT:20,OPEN_TIME:'08:00',CLOSE_TIME:'17:00',SLOT_MINUTES:30},blocks:[],page:'advance',viewMode:'week',weekStart:startOfWeek(new Date()),day:new Date(),selected:null,editing:null};
const $=id=>document.getElementById(id);
const safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function startOfWeek(d){d=new Date(d);const day=d.getDay()||7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day+1);return d}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function normaliseTime(v){const m=String(v||'').match(/^(\d{1,2}):(\d{2})/);return m?`${String(+m[1]).padStart(2,'0')}:${m[2]}`:''}
function showToast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2600)}
function session(){return JSON.parse(sessionStorage.getItem('apm_session')||'null')}
function saveSession(){sessionStorage.setItem('apm_session',JSON.stringify({user:state.user,token:state.token}))}
function clearSession(){sessionStorage.removeItem('apm_session')}
function api(action,params={}){const url=CFG.API_URL;if(!url||url.includes('PASTE_YOUR'))return Promise.reject(new Error('The Apps Script URL has not been added to config.js.'));return new Promise((resolve,reject)=>{const cb=`apm_${Date.now()}_${Math.random().toString(36).slice(2)}`,s=document.createElement('script');let done=false;const timeout=setTimeout(()=>finish(new Error('Request timed out.')),20000);function finish(err,data){if(done)return;done=true;clearTimeout(timeout);delete window[cb];s.remove();err?reject(err):resolve(data)}window[cb]=data=>data&&data.ok===false?finish(new Error(data.error||'Request failed')):finish(null,data);const q=new URLSearchParams({action,callback:cb,...params});if(state.user){q.set('user',state.user.name);q.set('token',state.token)}s.src=`${url}?${q}`;s.onerror=()=>finish(new Error('Could not contact Google Apps Script.'));document.body.appendChild(s)})}
async function login(e){e.preventDefault();$('loginError').textContent='';try{const r=await api('login',{name:$('loginName').value.trim(),accessKey:$('loginKey').value});state.user=r.user;state.token=r.sessionToken;saveSession();await enterApp()}catch(err){$('loginError').textContent=err.message}}
async function enterApp(){try{const b=await api('bootstrap');state.user=b.user;state.team=b.team||[];state.config=b.config||state.config;state.blocks=b.blocks||[];$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');updateUserChip();await loadData();setPage('advance')}catch(err){clearSession();$('loginScreen').classList.remove('hidden');$('app').classList.add('hidden');$('loginError').textContent=err.message}}
async function loadData(){const from=localDate(state.viewMode==='day'?state.day:state.weekStart),to=localDate(state.viewMode==='day'?state.day:addDays(state.weekStart,6));try{const r=await api('list',{from,to});state.bookings=r.bookings||[];state.activity=r.activity||[];state.team=r.team||state.team;state.config=r.config||state.config;state.blocks=r.blocks||state.blocks;renderAll()}catch(e){showToast(e.message)}}
function updateUserChip(){if(!state.user)return;$('userName').textContent=state.user.name;$('userRole').textContent=state.user.role;renderAvatar($('userAvatar'),state.user)}
function renderAvatar(el,user){if(user.profileImage){el.textContent='';el.style.backgroundImage=`url(${user.profileImage})`}else{el.style.backgroundImage='none';const idx=Math.max(0,Number(String(user.avatar||'avatar-1').split('-')[1])-1);el.textContent=AVATARS[idx]||AVATARS[0]}}
function setPage(p){state.page=p;document.querySelectorAll('.sidebar [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));const titles={dashboard:['Dashboard','Overview of today’s Trade Counter workload'],advance:['Advance Picks','View and manage timed large-order collections'],small:['Small Orders','Manage small orders and walk-in collections'],board:['Picking Board','Prioritise and progress all picking work'],workload:['Team Workload','Review picker assignments and workload'],reports:['Reports','Customer service, picking and sales performance'],settings:['Settings','Manage your profile and application settings']};$('pageTitle').textContent=titles[p][0];$('pageSubtitle').textContent=titles[p][1];$('plannerControls').classList.toggle('hidden',['dashboard','reports','settings'].includes(p));$('filterPanel').classList.add('hidden');$('stats').classList.toggle('hidden',['settings','reports'].includes(p));renderAll();if(p==='settings')openSettings()}
function filtered(){const q=$('searchInput').value.toLowerCase(),sf=$('statusFilter').value,pf=$('pickerFilter').value,pr=$('priorityFilter').value;return state.bookings.filter(b=>(!q||`${b.orderNumber} ${b.customer}`.toLowerCase().includes(q))&&(!sf||displayStatus(b)===sf)&&(!pf||b.assignedPicker===pf)&&(!pr||b.priority===pr))}
function displayStatus(b){return b.collectionStatus==='Collected'?'Collected':b.collectionStatus==='Customer Waiting'?'Customer Waiting':b.pickStatus||'Waiting'}
function renderAll(){renderDateLabel();renderFilters();renderStats();renderNotifications();if(state.page==='dashboard')renderDashboard();else if(state.page==='advance')renderTimedCalendar();else if(state.page==='small')renderSmallCalendar();else if(state.page==='board')renderBoard();else if(state.page==='workload')renderWorkload();else if(state.page==='reports')renderReports();}
function renderDateLabel(){const start=state.viewMode==='day'?state.day:state.weekStart,end=state.viewMode==='day'?state.day:addDays(state.weekStart,6);$('dateLabel').textContent=state.viewMode==='day'?start.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'}):`${start.toLocaleDateString('en-GB',{day:'numeric',month:'short'})} – ${end.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}`;$('viewMode').value=state.viewMode}
function renderFilters(){const statuses=['Waiting','Picking','Ready','Customer Waiting','Collected','Problem','Cancelled'];const current=$('statusFilter').value;$('statusFilter').innerHTML='<option value="">All statuses</option>'+statuses.map(s=>`<option>${s}</option>`).join('');$('statusFilter').value=current;const pc=$('pickerFilter').value;$('pickerFilter').innerHTML='<option value="">All pickers</option>'+state.team.filter(t=>t.active).map(t=>`<option>${safe(t.name)}</option>`).join('');$('pickerFilter').value=pc;const sel=$('assignedPicker');if(sel){const v=sel.value;sel.innerHTML='<option value="">Unassigned</option>'+state.team.filter(t=>t.active).map(t=>`<option>${safe(t.name)}</option>`).join('');sel.value=v}}
function renderStats(){const b=filtered(),ready=b.filter(x=>x.pickStatus==='Ready').length,picking=b.filter(x=>x.pickStatus==='Picking').length,waiting=b.filter(x=>x.pickStatus==='Waiting').length,issues=b.filter(x=>['Problem','Cancelled'].includes(x.pickStatus)||isLate(x)).length;const cards=[['▣','Collections',b.length,'Current selected period'],['✓','Ready for Collection',ready,`${pct(ready,b.length)}% of bookings`],['⇆','Being Picked',picking,`${pct(picking,b.length)}% of bookings`],['◷','Waiting to Pick',waiting,`${pct(waiting,b.length)}% of bookings`],['!','Issues / Overdue',issues,issues?'Requires attention':'No current issues']];$('stats').innerHTML=cards.map(c=>`<div class="stat"><div class="stat-icon">${c[0]}</div><span>${c[1]}</span><strong>${c[2]}</strong><small>${c[3]}</small></div>`).join('')}
function pct(a,b){return b?Math.round(a/b*100):0}
function nowLondon(){return new Date()}
function isLate(b){if(!b.collectionTime||b.collectionStatus==='Collected'||b.pickStatus==='Cancelled')return false;return new Date(`${b.collectionDate}T${b.collectionTime}:00`)<nowLondon()}
function needsPickSoon(b){if(!b.collectionTime||['Ready'].includes(b.pickStatus)||b.collectionStatus==='Collected'||b.pickStatus==='Cancelled')return false;const t=new Date(`${b.collectionDate}T${b.collectionTime}:00`);return t-nowLondon()<=30*60000&&t-nowLondon()>0}
function notifications(){return state.bookings.flatMap(b=>{const arr=[];if(isLate(b))arr.push({type:'Overdue',b,msg:'Collection time has passed'});if(needsPickSoon(b))arr.push({type:'Pick due',b,msg:'Not ready within 30 minutes of collection'});if(['Problem','Cancelled'].includes(b.pickStatus))arr.push({type:b.pickStatus,b,msg:b.pickStatus==='Problem'?'Order has a problem':'Booking is cancelled'});return arr})}
function renderNotifications(){const n=notifications();$('notificationBadge').textContent=n.length;$('notificationBadge').classList.toggle('hidden',!n.length);$('notificationList').innerHTML=n.length?n.map(x=>`<div class="notice" data-id="${x.b.id}"><strong>${safe(x.type)} · ${safe(x.b.orderNumber)}</strong><span>${safe(x.b.customer)}</span><small>${safe(x.msg)}</small></div>`).join(''):'<p>No current notifications.</p>';document.querySelectorAll('.notice').forEach(x=>x.onclick=()=>openOrder(x.dataset.id))}
function timeSlots(date){const start=normaliseTime(state.config.OPEN_TIME||'08:00'),end=normaliseTime(state.config.CLOSE_TIME||'17:00'),step=Number(state.config.SLOT_MINUTES||30),out=[];let [h,m]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number);for(let cur=h*60+m;cur<eh*60+em;cur+=step)out.push(`${String(Math.floor(cur/60)).padStart(2,'0')}:${String(cur%60).padStart(2,'0')}`);return out}
function isBlocked(date,time){const day=new Date(date+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long'});return state.blocks.find(b=>b.active&&b.dayOfWeek===day&&time>=b.startTime&&time<b.endTime)}
function visibleDays(){return state.viewMode==='day'?[new Date(state.day)]:[0,1,2,3,4].map(i=>addDays(state.weekStart,i))}
function card(b){const status=displayStatus(b),held=b.accountStatus==='Held'?'<span class="pill p-Held">HELD</span>':'';return `<article class="booking-card status-${safe(b.pickStatus)}" draggable="true" data-id="${safe(b.id)}"><div class="card-row"><strong>${safe(b.orderNumber)}</strong>${b.collectionTime?`<b>${safe(b.collectionTime)}</b>`:''}</div><span class="customer">${safe(b.customer)}</span><div class="card-row"><span>${Number(b.itemCount||0)} items</span><span class="pill p-${safe(status)}">${safe(status)}</span></div><div class="card-row"><span>${safe(b.bookingType)}</span>${held}</div>${b.priority!=='Normal'?`<div class="card-row"><span class="pill p-Problem">${safe(b.priority)} priority</span></div>`:''}</article>`}
function renderTimedCalendar(){const days=visibleDays(),bookings=filtered().filter(b=>b.bookingType==='Advance Large Order');let html=`<div class="calendar-wrap ${state.viewMode==='day'?'day-view':''}"><div class="calendar-grid"><div class="cal-cell cal-head"></div>${days.map(d=>`<div class="cal-cell cal-head">${d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})}</div>`).join('')}`;for(const time of timeSlots()){html+=`<div class="cal-cell time-cell">${time}</div>`;for(const d of days){const date=localDate(d),block=isBlocked(date,time);html+=`<div class="cal-cell slot ${block?'blocked':''}" data-date="${date}" data-time="${time}">${block?safe(block.label||'Blocked'):bookings.filter(b=>b.collectionDate===date&&normaliseTime(b.collectionTime)===time).map(b=>card(b)).join('')}</div>`}}html+='</div></div>';$('pageBody').innerHTML=html;wireCards()}
function renderSmallCalendar(){const days=visibleDays(),b=filtered().filter(x=>['Small Order','Walk in'].includes(x.bookingType));$('pageBody').innerHTML=`<div class="small-calendar">${days.map(d=>{const date=localDate(d);return `<section class="day-column" data-date="${date}"><h3>${d.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'short'})}</h3>${b.filter(x=>x.collectionDate===date).sort(sortBookings).map(b=>card(b,{showTime:true})).join('')}</section>`}).join('')}</div>`;wireCards()}
function sortBookings(a,b){return `${a.collectionTime||'99:99'}${a.priority}`.localeCompare(`${b.collectionTime||'99:99'}${b.priority}`)}
function renderBoard(){const all=filtered().filter(b=>state.viewMode==='week'||b.collectionDate===localDate(state.day));const renderSection=(title,items)=>`<div class="board-section"><h2>${title}</h2><div class="board">${PICK_STATUSES.map(s=>`<section class="board-col"><div class="board-head"><span>${s}</span><span>${items.filter(b=>b.pickStatus===s).length}</span></div><div class="board-list" data-status="${s}">${items.filter(b=>b.pickStatus===s).sort(sortBookings).map(b=>card(b,{showTime:true})).join('')}</div></section>`).join('')}</div></div>`;$('pageBody').innerHTML=renderSection('Advance Picks',all.filter(b=>b.bookingType==='Advance Large Order'))+renderSection('Small Orders / Walk ins',all.filter(b=>b.bookingType!=='Advance Large Order'));wireCards()}
function renderWorkload(){const b=filtered().filter(x=>state.viewMode==='week'||x.collectionDate===localDate(state.day));$('pageBody').innerHTML=`<div class="workload-grid">${state.team.filter(t=>t.active).map(t=>{const jobs=b.filter(x=>x.assignedPicker===t.name&&x.pickStatus!=='Cancelled'&&x.collectionStatus!=='Collected'),ready=jobs.filter(x=>x.pickStatus==='Ready').length,p=Math.min(100,jobs.length*15);return `<div class="person-card"><div class="card-row"><h3>${safe(t.name)}</h3><span>${safe(t.role)}</span></div><p>${jobs.length} active bookings · ${ready} ready</p><div class="progress"><div style="width:${p}%"></div></div>${jobs.slice(0,4).map(b=>card(b,{showTime:true})).join('')}</div>`}).join('')}</div>`;wireCards()}
function renderDashboard(){const today=localDate(new Date()),b=state.bookings.filter(x=>x.collectionDate===today);$('pageBody').innerHTML=`<div class="dashboard-grid"><div class="dashboard-card">Today’s Collections<strong>${b.length}</strong></div><div class="dashboard-card">Waiting to Pick<strong>${b.filter(x=>x.pickStatus==='Waiting').length}</strong></div><div class="dashboard-card">Ready<strong>${b.filter(x=>x.pickStatus==='Ready').length}</strong></div><div class="dashboard-card">Customer Waiting<strong>${b.filter(x=>x.collectionStatus==='Customer Waiting').length}</strong></div></div><h2>Today’s Queue</h2><div class="small-calendar"><section class="day-column">${b.sort(sortBookings).map(b=>card(b,{showTime:true})).join('')||'<p>No bookings today.</p>'}</section></div>`;wireCards()}
async function renderReports(){const from=localDate(state.viewMode==='day'?state.day:state.weekStart),to=localDate(state.viewMode==='day'?state.day:addDays(state.weekStart,6));$('pageBody').innerHTML='<p>Loading reports…</p>';try{const r=await api('reports',{from,to}),s=r.summary;$('pageBody').innerHTML=`<div class="report-grid"><div class="report-card">Bookings<strong>${s.bookings}</strong></div><div class="report-card">Average Customer Wait<strong>${s.averageWaitMinutes} min</strong></div><div class="report-card">Average Pick Time<strong>${s.averagePickMinutes} min</strong></div><div class="report-card">Sales inc VAT<strong>£${Number(s.totalSalesIncVAT).toLocaleString('en-GB',{minimumFractionDigits:2})}</strong></div></div><h2>Daily Breakdown</h2><table class="table"><thead><tr><th>Date</th><th>Bookings</th><th>Collected</th><th>Sales ex VAT</th><th>Sales inc VAT</th></tr></thead><tbody>${Object.entries(r.byDay).sort().map(([d,x])=>`<tr><td>${d}</td><td>${x.bookings}</td><td>${x.collected}</td><td>£${x.salesExVAT.toFixed(2)}</td><td>£${x.salesIncVAT.toFixed(2)}</td></tr>`).join('')}</tbody></table>`}catch(e){$('pageBody').innerHTML=`<p>${safe(e.message)}</p>`}}
function wireCards(){document.querySelectorAll('.booking-card').forEach(el=>{el.onclick=()=>openOrder(el.dataset.id);el.ondragstart=e=>e.dataTransfer.setData('text/plain',el.dataset.id)});document.querySelectorAll('.slot:not(.blocked)').forEach(el=>{el.ondragover=e=>{e.preventDefault();el.classList.add('drag-over')};el.ondragleave=()=>el.classList.remove('drag-over');el.ondrop=e=>{e.preventDefault();quickUpdate(e.dataTransfer.getData('text/plain'),{collectionDate:el.dataset.date,collectionTime:el.dataset.time})}});document.querySelectorAll('.day-column').forEach(el=>{el.ondragover=e=>e.preventDefault();el.ondrop=e=>quickUpdate(e.dataTransfer.getData('text/plain'),{collectionDate:el.dataset.date})});document.querySelectorAll('.board-list').forEach(el=>{el.ondragover=e=>e.preventDefault();el.ondrop=e=>quickUpdate(e.dataTransfer.getData('text/plain'),{pickStatus:el.dataset.status})})}
async function quickUpdate(id,changes){try{await api('quick',{id,changes:JSON.stringify(changes)});showToast('Booking updated');await loadData()}catch(e){showToast(e.message)}}
function openOrder(id){state.selected=state.bookings.find(b=>b.id===id);if(!state.selected)return;$('orderPanelTitle').textContent=state.selected.orderNumber||'Order';$('orderPanelStatus').innerHTML=`<span class="pill status ${displayStatus(state.selected).toLowerCase().replace(/\s+/g,'-')}">${safe(displayStatus(state.selected))}</span>`;$('orderPanel').classList.remove('hidden');renderOrderTab('details')}
function renderOrderTab(tab){const b=state.selected;if(!b)return;$('orderPanelTitle').textContent=b.orderNumber;$('orderPanelStatus').innerHTML=`<span class="pill p-${safe(displayStatus(b))}">${safe(displayStatus(b))}</span>`;document.querySelectorAll('[data-order-tab]').forEach(x=>x.classList.toggle('active',x.dataset.orderTab===tab));if(tab==='details'){$('orderPanelContent').innerHTML=`<div class="tracker">${['Waiting','Picking','Ready','Collected'].map((s,i)=>`<div class="tracker-step ${trackerDone(b,i)?'done':''}">${s}</div>`).join('')}</div><div class="detail-list">${detail('Customer',b.customer)}${detail('Collection',`${b.collectionDate}${b.collectionTime?' at '+b.collectionTime:''}`)}${detail('Booking Type',b.bookingType)}${detail('Items',b.itemCount)}${detail('Payment',`${b.paymentType||'-'} · ${b.paymentStatus||'-'}`)}${detail('Account',b.accountStatus||'-')}${detail('Assigned Picker',b.assignedPicker||'Unassigned')}${detail('Priority',b.priority)}${detail('Order Value',`£${Number(b.orderValueExVAT||0).toFixed(2)} ex VAT / £${Number(b.orderValueIncVAT||0).toFixed(2)} inc VAT`)}${detail('Booked By',b.bookedBy||'-')}${detail('Requirements',requirements(b)||'None')}</div>`}else if(tab==='notes')$('orderPanelContent').innerHTML=`<p>${safe(b.notes||'No notes recorded.')}</p>`;else{$('orderPanelContent').innerHTML=(state.activity.filter(a=>a.bookingId===b.id).sort((a,z)=>z.timestamp.localeCompare(a.timestamp)).map(a=>`<div class="activity-item"><strong>${safe(a.action)}</strong><div>${safe(a.details)}</div><small>${safe(a.performedBy)} · ${safe(formatDateTime(a.timestamp))}</small></div>`).join('')||'<p>No activity recorded.</p>')};$('panelWaiting').disabled=b.collectionStatus==='Collected';$('panelReady').disabled=b.pickStatus==='Ready';$('panelCollected').disabled=b.collectionStatus==='Collected'}
function trackerDone(b,i){if(i===0)return true;if(i===1)return ['Picking','Ready'].includes(b.pickStatus)||b.collectionStatus==='Collected';if(i===2)return b.pickStatus==='Ready'||b.collectionStatus==='Collected';return b.collectionStatus==='Collected'}
function detail(a,b){return `<div class="detail-row"><span>${a}</span><strong>${safe(b)}</strong></div>`}
function requirements(b){return [['Drilling',b.drillingRequired],['Parkway',b.parkwayItems],['Air Picks',b.airPicks],['O/S',b.osItems],['Painted',b.paintedOrder],['MTM',b.madeToMeasure]].filter(x=>x[1]).map(x=>x[0]).join(', ')}
function formatDateTime(v){return v?new Date(v).toLocaleString('en-GB'):'-'}
function validWeekday(date){const d=new Date(date+'T12:00:00').getDay();return d!==0&&d!==6}
function updateTimeOptions(){const date=$('collectionDate').value,type=$('bookingType').value,current=$('collectionTime').value;$('collectionTime').innerHTML=`<option value="">${type==='Advance Large Order'?'Select a time':'No fixed time'}</option>`+timeSlots().map(t=>`<option value="${t}" ${date&&isBlocked(date,t)?'disabled':''}>${t}${date&&isBlocked(date,t)?' – Blocked':''}</option>`).join('');$('collectionTime').required=type==='Advance Large Order';$('collectionTime').value=current}
function openBooking(id){state.editing=id?state.bookings.find(x=>x.id===id):null;const b=state.editing||{collectionDate:localDate(new Date()),bookingType:'Advance Large Order',pickStatus:'Waiting',paymentStatus:'Payment Required',accountStatus:'Released',priority:'Normal'};$('modalTitle').textContent=id?`Edit ${b.orderNumber}`:'New Booking';const fields=['bookingId','orderNumber','customer','bookingType','itemCount','collectionDate','collectionTime','assignedPicker','priority','paymentType','paymentStatus','accountStatus','pickStatus','collectionStatus','bookedBy','orderValueExVAT','orderValueIncVAT','notes'];fields.forEach(k=>{const el=$(k),key=k==='bookingId'?'id':k;if(el)el.value=b[key]??''});['drillingRequired','parkwayItems','airPicks','osItems','paintedOrder','madeToMeasure'].forEach(k=>$(k).checked=!!b[k]);updateTimeOptions();$('collectionTime').value=b.collectionTime||'';$('deleteBookingBtn').classList.toggle('hidden',!id);$('bookingModal').classList.remove('hidden');calcVat()}
function calcVat(){const ex=Number($('orderValueExVAT').value||0),vat=Number(state.config.VAT_PERCENT||20);$('orderValueIncVAT').value=(ex*(1+vat/100)).toFixed(2)}
async function saveBooking(e){e.preventDefault();if(!validWeekday($('collectionDate').value)){showToast('Collection dates must be Monday to Friday.');return}const fields=['bookingId','orderNumber','customer','bookingType','itemCount','collectionDate','collectionTime','assignedPicker','priority','paymentType','paymentStatus','accountStatus','pickStatus','collectionStatus','bookedBy','orderValueExVAT','notes'];const b={};fields.forEach(k=>b[k==='bookingId'?'id':k]=$(k).value);['drillingRequired','parkwayItems','airPicks','osItems','paintedOrder','madeToMeasure'].forEach(k=>b[k]=$(k).checked);try{await api('save',{payload:JSON.stringify(b)});$('bookingModal').classList.add('hidden');showToast('Booking saved');await loadData()}catch(err){showToast(err.message)}}
async function deleteBooking(){if(!state.editing||!confirm(`Delete ${state.editing.orderNumber}?`))return;try{await api('delete',{id:state.editing.id});$('bookingModal').classList.add('hidden');$('orderPanel').classList.add('hidden');showToast('Booking deleted');await loadData()}catch(e){showToast(e.message)}}
function openSettings(){renderSettings();$('settingsModal').classList.remove('hidden')}
function renderSettings(){const manager=state.user.role==='Manager';$('settingsContent').innerHTML=`<div class="settings-grid"><section class="settings-section"><h3>My Profile</h3><p>${safe(state.user.name)} · ${safe(state.user.role)}</p><label>New Access Key<input id="ownNewKey" type="password"></label><button id="changeOwnKey">Change Access Key</button><h4>Choose Avatar</h4><div class="avatar-options">${AVATARS.map((a,i)=>`<button class="avatar-choice ${(state.user.avatar===`avatar-${i+1}`)?'selected':''}" data-avatar="avatar-${i+1}">${a}</button>`).join('')}</div><label>Upload Selfie<input id="profileUpload" type="file" accept="image/*"></label><small>Images are compressed before being saved.</small></section>${manager?`<section class="settings-section"><h3>Application Settings</h3><label>Opening Time<input id="cfgOpen" type="time" step="1800" value="${safe(state.config.OPEN_TIME||'08:00')}"></label><label>Closing Time<input id="cfgClose" type="time" step="1800" value="${safe(state.config.CLOSE_TIME||'17:00')}"></label><label>VAT Percentage<input id="cfgVat" type="number" step="0.01" value="${safe(state.config.VAT_PERCENT||20)}"></label><button id="saveConfigBtn">Save Settings</button></section><section class="settings-section"><h3>Users</h3><div id="userRows">${state.team.map(userRow).join('')}</div><button id="addUserBtn">＋ Add User</button></section><section class="settings-section"><h3>Blocked Booking Times</h3><div>${state.blocks.map(blockRow).join('')}</div><button id="addBlockBtn">＋ Add Blocked Time</button></section>`:''}</div>`;wireSettings(manager)}
function userRow(u){return `<div class="notice"><strong>${safe(u.name)}</strong><span>${safe(u.role)} · ${u.active?'Active':'Inactive'}</span><div><button data-edit-user="${safe(u.name)}">Edit</button><button data-delete-user="${safe(u.name)}">Delete</button></div></div>`}
function blockRow(b){return `<div class="notice"><strong>${safe(b.dayOfWeek)} ${safe(b.startTime)}–${safe(b.endTime)}</strong><span>${safe(b.label)}</span><div><button data-edit-block="${b.id}">Edit</button><button data-delete-block="${b.id}">Delete</button></div></div>`}
function wireSettings(manager){$('changeOwnKey').onclick=async()=>{try{const r=await api('changeKey',{newKey:$('ownNewKey').value});state.token=r.sessionToken;saveSession();showToast('Access key changed')}catch(e){showToast(e.message)}};document.querySelectorAll('[data-avatar]').forEach(x=>x.onclick=async()=>{try{await api('setAvatar',{avatar:x.dataset.avatar});state.user.avatar=x.dataset.avatar;state.user.profileImage='';saveSession();updateUserChip();renderSettings()}catch(e){showToast(e.message)}});$('profileUpload').onchange=uploadProfile;if(manager){$('saveConfigBtn').onclick=async()=>{try{const r=await api('saveConfig',{payload:JSON.stringify({OPEN_TIME:$('cfgOpen').value,CLOSE_TIME:$('cfgClose').value,VAT_PERCENT:$('cfgVat').value})});state.config=r.config;showToast('Settings saved');renderSettings();renderAll()}catch(e){showToast(e.message)}};$('addUserBtn').onclick=()=>editUser();document.querySelectorAll('[data-edit-user]').forEach(x=>x.onclick=()=>editUser(x.dataset.editUser));document.querySelectorAll('[data-delete-user]').forEach(x=>x.onclick=()=>deleteUser(x.dataset.deleteUser));$('addBlockBtn').onclick=()=>editBlock();document.querySelectorAll('[data-edit-block]').forEach(x=>x.onclick=()=>editBlock(x.dataset.editBlock));document.querySelectorAll('[data-delete-block]').forEach(x=>x.onclick=()=>deleteBlock(x.dataset.deleteBlock))}}
function editUser(name=''){const u=state.team.find(x=>x.name===name)||{name:'',role:'Trade Counter',active:true};const n=prompt('User name',u.name);if(n===null)return;const role=prompt('Role: Manager, Trade Counter or Warehouse',u.role);if(role===null)return;const key=prompt('Access key (leave blank to retain/generate)', '');if(key===null)return;const active=confirm('Click OK for Active, or Cancel for Inactive.');api('saveUser',{payload:JSON.stringify({originalName:u.name,name:n,role,accessKey:key,active})}).then(r=>{state.team=r.team;renderSettings();showToast('User saved')}).catch(e=>showToast(e.message))}
function deleteUser(name){if(!confirm(`Delete user ${name}?`))return;api('deleteUser',{name}).then(r=>{state.team=r.team;renderSettings()}).catch(e=>showToast(e.message))}
function editBlock(id=''){const b=state.blocks.find(x=>x.id===id)||{dayOfWeek:'Monday',startTime:'08:00',endTime:'08:30',label:'Team checks',active:true};const day=prompt('Day of week',b.dayOfWeek);if(day===null)return;const start=prompt('Start time (HH:mm)',b.startTime);if(start===null)return;const end=prompt('End time (HH:mm)',b.endTime);if(end===null)return;const label=prompt('Label',b.label);if(label===null)return;api('saveBlock',{payload:JSON.stringify({id:b.id,dayOfWeek:day,startTime:start,endTime:end,label,active:true})}).then(r=>{state.blocks=r.blocks;renderSettings();renderAll()}).catch(e=>showToast(e.message))}
function deleteBlock(id){if(!confirm('Delete this blocked time?'))return;api('deleteBlock',{id}).then(r=>{state.blocks=r.blocks;renderSettings();renderAll()}).catch(e=>showToast(e.message))}
async function uploadProfile(e){const file=e.target.files[0];if(!file)return;try{const data=await resizeImage(file,120,120,.72),uploadId=Date.now()+'_'+Math.random().toString(36).slice(2),chunks=data.match(/.{1,1200}/g)||[];for(let i=0;i<chunks.length;i++)await api('saveProfileChunk',{uploadId,index:i,total:chunks.length,chunk:chunks[i]});state.user.profileImage=data;saveSession();updateUserChip();showToast('Profile image saved')}catch(err){showToast(err.message)}}
function resizeImage(file,w,h,q){return new Promise((resolve,reject)=>{const img=new Image(),r=new FileReader();r.onload=()=>img.src=r.result;r.onerror=reject;img.onload=()=>{const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d'),scale=Math.max(w/img.width,h/img.height),sw=w/scale,sh=h/scale,sx=(img.width-sw)/2,sy=(img.height-sh)/2;ctx.drawImage(img,sx,sy,sw,sh,0,0,w,h);resolve(c.toDataURL('image/jpeg',q))};r.readAsDataURL(file)})}

$('loginForm').onsubmit=login;$('logoutBtn').onclick=()=>{clearSession();location.reload()};document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>setPage(x.dataset.page));$('newBookingBtn').onclick=()=>openBooking();$('bookingForm').onsubmit=saveBooking;$('deleteBookingBtn').onclick=deleteBooking;$('orderValueExVAT').oninput=calcVat;$('bookingType').onchange=updateTimeOptions;$('collectionDate').onchange=()=>{if(!validWeekday($('collectionDate').value)){showToast('Please choose Monday to Friday.');$('collectionDate').value=''}updateTimeOptions()};$('filterBtn').onclick=()=>$('filterPanel').classList.toggle('hidden');$('clearFilters').onclick=()=>{$('statusFilter').value='';$('pickerFilter').value='';$('priorityFilter').value='';renderAll()};[$('searchInput'),$('statusFilter'),$('pickerFilter'),$('priorityFilter')].forEach(x=>x.addEventListener(x.tagName==='INPUT'?'input':'change',renderAll));$('viewMode').onchange=()=>{state.viewMode=$('viewMode').value;loadData()};$('prevBtn').onclick=()=>{if(state.viewMode==='day')state.day=addDays(state.day,-1);else state.weekStart=addDays(state.weekStart,-7);loadData()};$('nextBtn').onclick=()=>{if(state.viewMode==='day')state.day=addDays(state.day,1);else state.weekStart=addDays(state.weekStart,7);loadData()};$('todayBtn').onclick=()=>{state.day=new Date();state.weekStart=startOfWeek(new Date());loadData()};$('refreshBtn').onclick=loadData;$('notificationBtn').onclick=()=>$('notificationPanel').classList.toggle('hidden');document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>$(x.dataset.close).classList.add('hidden'));document.querySelectorAll('[data-order-tab]').forEach(x=>x.onclick=()=>renderOrderTab(x.dataset.orderTab));$('panelEdit').onclick=()=>openBooking(state.selected.id);$('panelReady').onclick=()=>quickUpdate(state.selected.id,{pickStatus:'Ready'});$('panelWaiting').onclick=()=>quickUpdate(state.selected.id,{collectionStatus:'Customer Waiting'});$('panelCollected').onclick=()=>quickUpdate(state.selected.id,{collectionStatus:'Collected'});
PAYMENT_TYPES.forEach(x=>$('paymentType').add(new Option(x,x)));
const s=session();if(s){state.user=s.user;state.token=s.token;enterApp()}else $('loginScreen').classList.remove('hidden');

window.APM_APP_LOADED=true;

/* ===== Trade Counter Operations Hub v1.3 refinements ===== */
function setLoading(active,text='Loading…'){
  const overlay=$('loadingOverlay'); if(!overlay)return;
  $('loadingText').textContent=text; overlay.classList.toggle('hidden',!active);
}
function showToast(msg,type='success'){
  const t=$('toast'); t.textContent=msg; t.classList.toggle('error',type==='error'); t.classList.remove('hidden');
  clearTimeout(showToast.timer); showToast.timer=setTimeout(()=>t.classList.add('hidden'),3000);
}
async function login(e){
  e.preventDefault(); $('loginError').textContent=''; setLoading(true,'Signing you in…');
  try{const r=await api('login',{name:$('loginName').value.trim(),accessKey:$('loginKey').value});state.user=r.user;state.token=r.sessionToken;saveSession();await enterApp()}
  catch(err){$('loginError').textContent=err.message}
  finally{setLoading(false)}
}
async function loadData(){
  const from=localDate(state.viewMode==='day'?state.day:state.weekStart),to=localDate(state.viewMode==='day'?state.day:addDays(state.weekStart,6));
  setLoading(true,'Updating Trade Counter information…');
  try{const r=await api('list',{from,to});state.bookings=r.bookings||[];state.activity=r.activity||[];state.team=r.team||state.team;state.config=r.config||state.config;state.blocks=r.blocks||state.blocks;renderAll()}
  catch(e){showToast(e.message,'error')}
  finally{setLoading(false)}
}
function setPage(p){
  state.page=p; document.querySelectorAll('.sidebar [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));
  const titles={dashboard:['Dashboard','Today’s operational overview and team workload'],advance:['Advance Picks','View and manage timed large-order collections'],small:['Small Orders','Manage small orders and walk-in collections'],board:['Picking Board','Prioritise and progress all picking work'],reports:['Reports','Customer service, picking and sales performance'],settings:['Settings','Manage your profile and application settings']};
  $('pageTitle').textContent=titles[p][0]; $('pageSubtitle').textContent=titles[p][1];
  $('plannerControls').classList.toggle('hidden',['dashboard','reports','settings'].includes(p)); $('filterPanel').classList.add('hidden'); $('stats').classList.toggle('hidden',['settings','reports'].includes(p));
  renderAll(); if(p==='settings')openSettings();
}
function renderStats(){
  const b=filtered(),ready=b.filter(x=>x.pickStatus==='Ready').length,picking=b.filter(x=>x.pickStatus==='Picking').length,waiting=b.filter(x=>x.pickStatus==='Waiting').length,issues=b.filter(x=>['Problem','Cancelled'].includes(x.pickStatus)||isLate(x)).length;
  const cards=[['▣','Collections',b.length,'Selected period'],['✓','Ready for Collection',ready,`${pct(ready,b.length)}% of bookings`],['⇆','Being Picked',picking,`${pct(picking,b.length)}% of bookings`],['◷','Waiting to Pick',waiting,`${pct(waiting,b.length)}% of bookings`],['!','Issues / Overdue',issues,issues?'Requires attention':'No current issues']];
  $('stats').innerHTML=cards.map(c=>`<div class="stat"><div class="stat-icon">${c[0]}</div><span>${c[1]}</span><strong>${c[2]}</strong><small title="${safe(c[3])}">${c[3]}</small></div>`).join('');
}
function requirementNames(b){return [['drillingRequired','Drilling'],['parkwayItems','Parkway'],['airPicks','Air Pick'],['osItems','O/S Items'],['paintedOrder','Painted'],['madeToMeasure','MTM']].filter(([k])=>b[k]).map(x=>x[1])}
function card(b,options={}){
  const status=displayStatus(b),priority=(b.priority||'Normal'),req=requirementNames(b),showTime=Boolean(options.showTime);
  return `<article class="booking-card status-${status.toLowerCase().replace(/\s+/g,'-')}" draggable="true" data-id="${b.id}">
    <div class="card-top"><span class="card-order">${safe(b.orderNumber)}</span>${priority!=='Normal'?`<span class="card-priority ${priority.toLowerCase()}">${safe(priority)}</span>`:''}</div>
    <div class="card-status-row"><span class="pill status ${status.toLowerCase().replace(/\s+/g,'-')}">${safe(status)}</span></div>
    <div class="card-customer">${safe(b.customer)}</div>
    <div class="card-meta">${Number(b.itemCount||0)} items${showTime&&b.collectionTime?` · ${safe(b.collectionTime)}`:''}</div>
    <div class="card-badges">${req.slice(0,3).map(r=>`<span class="pill requirement">${safe(r)}</span>`).join('')}${req.length>3?`<span class="pill requirement">+${req.length-3}</span>`:''}${b.accountStatus==='Held'?'<span class="pill held">Held</span>':''}</div>
  </article>`;
}
function renderOrderTab(tab){
  document.querySelectorAll('[data-order-tab]').forEach(x=>x.classList.toggle('active',x.dataset.orderTab===tab)); const b=state.selected;if(!b)return;
  if(tab==='notes'){$('orderPanelContent').innerHTML=`<div class="order-summary"><div class="summary-hero"><strong>Order notes</strong><p>${safe(b.notes||'No notes have been added.')}</p></div></div>`;return}
  if(tab==='activity'){const a=state.activity.filter(x=>x.bookingId===b.id).sort((x,y)=>String(y.timestamp).localeCompare(String(x.timestamp)));$('orderPanelContent').innerHTML=`<div class="order-summary">${a.length?a.map(x=>`<div class="notice"><strong>${safe(x.action)}</strong><span>${safe(x.details||'')}</span><small>${safe(x.performedBy)} · ${safe(formatDateTime(x.timestamp))}</small></div>`).join(''):'<div class="empty-state">No activity recorded.</div>'}</div>`;return}
  const req=requirementNames(b); const valEx=Number(b.orderValueExVAT||0).toLocaleString('en-GB',{style:'currency',currency:'GBP'}),valInc=Number(b.orderValueIncVAT||0).toLocaleString('en-GB',{style:'currency',currency:'GBP'});
  $('orderPanelTitle').textContent=b.orderNumber||'Order';
  $('orderPanelStatus').innerHTML=`<span class="pill status ${displayStatus(b).toLowerCase().replace(/\s+/g,'-')}">${safe(displayStatus(b))}</span>`;
  $('orderPanelContent').innerHTML=`<div class="order-summary">
    <div class="summary-hero"><div class="card-badges"><span class="pill status ${displayStatus(b).toLowerCase().replace(/\s+/g,'-')}">${safe(displayStatus(b))}</span>${b.priority!=='Normal'?`<span class="card-priority ${safe(b.priority.toLowerCase())}">${safe(b.priority)}</span>`:''}${b.accountStatus==='Held'?'<span class="pill held">Account Held</span>':''}</div><h3>${safe(b.customer)}</h3><p>${safe(b.bookingType)} · ${Number(b.itemCount||0)} items</p></div>
    <div class="tracker">${['Waiting','Picking','Ready','Collected'].map((s,i)=>`<div class="tracker-step ${trackerDone(b,i)?'done':''}">${s}</div>`).join('')}</div>
    <div class="summary-row"><span>Collection</span><strong>${safe(b.collectionDate)}${b.collectionTime?' at '+safe(b.collectionTime):''}</strong></div>
    <div class="summary-row"><span>Assigned picker</span><strong>${safe(b.assignedPicker||'Unassigned')}</strong></div>
    <div class="summary-row"><span>Payment</span><strong>${safe(b.paymentType||'—')} · ${safe(b.paymentStatus||'—')}</strong></div>
    <div class="summary-row"><span>Order value</span><strong>${valEx} ex VAT<br><small>${valInc} inc VAT</small></strong></div>
    <div class="summary-row"><span>Booked by</span><strong>${safe(b.bookedBy||'—')}</strong></div>
    <h4>Order requirements</h4><div class="requirement-pills">${req.length?req.map(r=>`<span class="pill requirement">${safe(r)}</span>`).join(''):'<span class="pill">No special requirements</span>'}</div>
  </div>`;
}
function renderDashboard(){
  const today=localDate(new Date()),todays=state.bookings.filter(b=>b.collectionDate===today).sort(sortBookings),waiting=todays.filter(b=>b.collectionStatus==='Customer Waiting'&&b.collectionStatus!=='Collected');
  const active=state.team.filter(t=>t.active&&t.role!=='Manager');
  const workload=active.map(t=>({name:t.name,count:todays.filter(b=>b.assignedPicker===t.name&&b.collectionStatus!=='Collected').length})); const max=Math.max(1,...workload.map(x=>x.count));
  $('pageBody').innerHTML=`<div class="dashboard-grid">
    <section class="dashboard-section"><h3>Today’s Queue</h3>${todays.length?todays.slice(0,12).map(b=>`<div class="queue-row" data-id="${b.id}"><strong>${safe(b.collectionTime||'Anytime')}</strong><span>${safe(b.orderNumber)} · ${safe(b.customer)}</span><span class="pill status">${safe(displayStatus(b))}</span></div>`).join(''):'<div class="empty-state">No collections today.</div>'}</section>
    <section class="dashboard-section"><h3>Customer Waiting</h3>${waiting.length?waiting.map(b=>`<div class="queue-row" data-id="${b.id}"><strong>${safe(b.collectionTime||'Now')}</strong><span>${safe(b.orderNumber)} · ${safe(b.customer)}</span><span class="pill held">Priority</span></div>`).join(''):'<div class="empty-state">No customers currently waiting.</div>'}</section>
    <section class="dashboard-section" style="grid-column:1/-1;border-top:1px solid var(--line);border-right:0"><h3>Team Workload</h3>${workload.length?workload.map(w=>`<div class="workload-row"><strong>${safe(w.name)}</strong><div class="workload-bar"><i style="width:${Math.round(w.count/max*100)}%"></i></div><span>${w.count} active</span></div>`).join(''):'<div class="empty-state">No active team members configured.</div>'}</section>
  </div>`; document.querySelectorAll('.queue-row[data-id]').forEach(x=>x.onclick=()=>openOrder(x.dataset.id));
}
let reportResult=null;
function renderReports(){
  $('pageBody').innerHTML=`<div class="report-shell"><div class="report-controls"><label>From date<input id="reportFrom" type="date"></label><label>To date<input id="reportTo" type="date"></label><button id="runReport" class="primary">Run Report</button></div><div id="reportResults">${reportResult?reportMarkup(reportResult):'<div class="empty-state"><strong>Select a date range</strong><p>Reports are only generated after you choose the period you want to review.</p></div>'}</div></div>`;
  $('runReport').onclick=async()=>{const from=$('reportFrom').value,to=$('reportTo').value;if(!from||!to){showToast('Select both a From and To date.','error');return}if(from>to){showToast('The From date must be before the To date.','error');return}setLoading(true,'Generating report…');try{reportResult=await api('reports',{from,to});$('reportResults').innerHTML=reportMarkup(reportResult)}catch(e){showToast(e.message,'error')}finally{setLoading(false)}};
}
function reportMarkup(r){const s=r.summary||{},days=r.byDay||{};return `<div class="stats" style="padding:16px;margin:0"><div class="stat"><div class="stat-icon">▣</div><span>Bookings</span><strong>${s.bookings||0}</strong><small>Selected range</small></div><div class="stat"><div class="stat-icon">✓</div><span>Collected</span><strong>${s.collected||0}</strong><small>Completed collections</small></div><div class="stat"><div class="stat-icon">◷</div><span>Average wait</span><strong>${s.averageWaitMinutes||0}m</strong><small>Waiting to collected</small></div><div class="stat"><div class="stat-icon">⇆</div><span>Average pick</span><strong>${s.averagePickMinutes||0}m</strong><small>Picking to ready</small></div><div class="stat"><div class="stat-icon">£</div><span>Sales inc VAT</span><strong>£${Number(s.totalSalesIncVAT||0).toLocaleString('en-GB',{minimumFractionDigits:2})}</strong><small>Selected range</small></div></div><table><thead><tr><th>Date</th><th>Bookings</th><th>Collected</th><th>Sales ex VAT</th><th>Sales inc VAT</th></tr></thead><tbody>${Object.keys(days).sort().map(d=>`<tr><td>${safe(d)}</td><td>${days[d].bookings}</td><td>${days[d].collected}</td><td>£${Number(days[d].salesExVAT).toFixed(2)}</td><td>£${Number(days[d].salesIncVAT).toFixed(2)}</td></tr>`).join('')||'<tr><td colspan="5">No records in this period.</td></tr>'}</tbody></table>`}
async function saveBooking(e){
  e.preventDefault();if(!validWeekday($('collectionDate').value)){showToast('Collection dates must be Monday to Friday.','error');return}
  const fields=['bookingId','orderNumber','customer','bookingType','itemCount','collectionDate','collectionTime','assignedPicker','priority','paymentType','paymentStatus','accountStatus','pickStatus','collectionStatus','bookedBy','orderValueExVAT','notes'],b={};fields.forEach(k=>b[k==='bookingId'?'id':k]=$(k).value);['drillingRequired','parkwayItems','airPicks','osItems','paintedOrder','madeToMeasure'].forEach(k=>b[k]=$(k).checked);
  const oldIndex=state.bookings.findIndex(x=>x.id===b.id),old=oldIndex>=0?{...state.bookings[oldIndex]}:null,temp={...(old||{}),...b,id:b.id||`temp-${Date.now()}`,orderValueIncVAT:Number(b.orderValueExVAT||0)*(1+Number(state.config.VAT_PERCENT||20)/100)};
  if(oldIndex>=0)state.bookings[oldIndex]=temp;else state.bookings.push(temp);$('bookingModal').classList.add('hidden');renderAll();showToast('Saving booking…');
  try{const r=await api('save',{payload:JSON.stringify(b)});const idx=state.bookings.findIndex(x=>x.id===temp.id);if(idx>=0)state.bookings[idx]=r.booking;showToast('Booking saved successfully');await loadData()}
  catch(err){if(oldIndex>=0)state.bookings[oldIndex]=old;else state.bookings=state.bookings.filter(x=>x.id!==temp.id);renderAll();showToast(`Booking was not saved: ${err.message}`,'error')}
}
async function quickUpdate(id,changes){
  const idx=state.bookings.findIndex(b=>b.id===id);if(idx<0)return;const before={...state.bookings[idx]};state.bookings[idx]={...before,...changes};state.selected=state.bookings[idx];renderAll();if(!$('orderPanel').classList.contains('hidden'))renderOrderTab('details');
  try{const r=await api('quick',{id,changes:JSON.stringify(changes)});state.bookings[idx]=r.booking;state.selected=r.booking;showToast('Order updated');renderAll();if(!$('orderPanel').classList.contains('hidden'))renderOrderTab('details')}
  catch(e){state.bookings[idx]=before;state.selected=before;renderAll();showToast(`Update failed: ${e.message}`,'error')}
}
// Replace the unusual diamond with a conventional bell shape without external libraries.
document.addEventListener('DOMContentLoaded',()=>{const bell=document.querySelector('.bell-icon');if(bell)bell.textContent='🔔'});
